cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'zsh'
brew 'zsh-completions'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'rustup'
brew 'mono'
brew 'glib'
brew 'pango'
brew 'atk'
brew 'gtk+3'
#brew llvm --with-lldb

cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
#cask 'steam'
cask 'spectacle'
#cask 'visual-studio-code'
#cask 'iterm2'

brew 'valgrind'

brew 'ripgrep'
brew 'pstree'
